### ISSUE TITLE
[Question] Migrating from 1.x to 4.5.1 : where are Catalog and CatalogSource classes ?

### ISSUE THREAD

**Issue by cmarchand** [xmlresolver/xmlresolver#116]
Hi Norm,

I'm migrating [xspec-maven-plugin](https://github.com/xspec/xspec-maven-plugin-1) to XMLResolver 4.5.1 for security reasons.

I was using Catalog and CatalogSource classes, but they do not exist anymore. What's the prefered way to adapt my code ?
[Concerned code](https://github.com/xspec/xspec-maven-plugin-1/blob/a433c1b24cf1fe9394effe0f425ed95805d4a08b/src/main/java/io/xspec/maven/xspecMavenPlugin/resolver/Resolver.java#L72) is quite limited and it should not be complicated.

Thanks in advance,
Christophe

**Comment by ndw** [comment]
If I understand the comment in that code, I think you can just use
```
   cr = new org.xmlresolver.Resolver();
```
That business about the global static catalog has gone away.

On the following line, I think what you want is:

```
  cr.getConfiguration().setFeature(ResolverFeature.CATALOG_FILES,
    Collections.singletonList(catalog.toURI().toString())
```

But let me know if you think I'm mistaken!

**Comment by cmarchand** [comment]
It seems to be Ok. Thanks a lot, Norm !
