### ISSUE TITLE
Open CatalogResolver API a bit

### ISSUE THREAD

**Issue by phax** [xmlresolver/xmlresolver#118]
Hi, I am in the middle of updating the Maven JAXB plugin to use your XML Resolver instead of the `com.sun.org.apache.xml.internal:resolver` artefact.

This plugin ships with its own `MavenCatalogResolver` that tries to resolve schemas from existing Maven artefacts. Therefore the class extends `CatalogResolver` and would overwrite the `resolveEntity` to add additional resolution logic.
Unfortunately the methods `resource` and `uncachedResource` are private. It would be great, if you could make them protected so that derived classes can also utilize them.

Thanks in advance

**Comment by phax** [comment]
Thanks a lot for the swift implementation ❤️

**Comment by ndw** [comment]
Happy to help. Let me know if you have any other questions or problems.
