### ISSUE TITLE
Avoid failing with unhandled exception when passed href has invalid URI characters

### ISSUE THREAD

**Issue by raducoravu** [xmlresolver/xmlresolver#149]
Based on this comment in a DITA Open Toolkit issue: https://github.com/dita-ot/dita-ot/issues/4218#issuecomment-1617669382
If the href passed to the XML resolver contains invalid URI chars like spaces, Windows backslashes in my opinion the resolver should not throw a IllegalArgumentException which is a runtime exception and is unexpected, it breaks the code calling the resolver. Probably the resolver should catch such problems internally and maybe log them, then return a null resolved source.

**Comment by ndw** [comment]
I have very mixed feelings about this. On the one hand, I see your point. On the other hand, it's not the resolver that's throwing the exception, it's `java.net.URI`. And there's the question of how this should interact with the ALWAYS_RESOLVE feature.

**Comment by ndw** [comment]
Ah. But in fact there's already a feature flag for this and I capture `URISyntaxException` and `IOException` so I think failing to catch `IllegalArgumentException` can be seen as an oversight.

**Comment by raducoravu** [comment]
Right, my opinion would be the resolver should be very robust and never break especially with runtime exceptions, if it cannot resolve anything, it returns null.

**Comment by raducoravu** [comment]
Thanks @ndw
