### ISSUE TITLE
Outdated 6.x JavaDoc?

### ISSUE THREAD

**Issue by chludwig-haufe** [xmlresolver/xmlresolver#167]
The JavaDoc link on [chapter 4 of the current (6.x) version's docs](https://xmlresolver.org/ch04) points to https://xmlresolver.org/javadoc/.  I didn't see any version information on the JavaDoc pages, but if I navigate from there to the [`org.xmlresolver` package summary](https://xmlresolver.org/javadoc/org/xmlresolver/package-summary), I still see a class `Resolver`, but no class `XMLResolver`.

I gather from Norman's blog post ["XML Resolver refactor refactor"](https://so.nwalsh.com/2024/01/27-xmlresolver) that the 6.0.0 release replaced the `Resolver` class by `XMLResolver`. Therefore, I assume that the JavaDoc is outdated.

Can you please fix the link or the JavaDoc version? (If it is easy to add, putting the version number of the code the JavaDoc was generated from might also be helpful.) Thanks!

**Comment by ndw** [comment]
Ah. Indeed. I thought that was part of the build, but it's part of the documentation build. I'll fix that over the weekend.

**Comment by ndw** [comment]
Fixed. Sorry about that.
