### ISSUE TITLE
Which java version.

### ISSUE THREAD

**Issue by jarl-dk** [xmlresolver/xmlresolver#173]
It is unclear what Java version the source code is supposed to build with.
* The badge and README says java 8
* The CI (github actions workflow) uses ubuntu-latest which is currently openjdk-17
* The gradle version in the project is version 8.5, which according to https://docs.gradle.org/current/userguide/compatibility.html indicates that java version 21 should be used.

Please align information and implementation. You should consider adding a `.sdkmanrc` file and use https://sdkman.io/

**Comment by ndw** [comment]
That's fair. The implementation produces `.class` files that are compatible with Java 8. That's the point that has historically been most important to library users, but the description should definitely be clarified.

I'll look into sdkman when I have a chance.
