### ISSUE TITLE
v6 seems to have no ability to resolve namespaces

### ISSUE THREAD

**Issue by pahjbo** [xmlresolver/xmlresolver#180]
Although namespaces are the "primary key" for [XSD schema language imports](https://www.w3.org/TR/xmlschema11-1/#composition-schemaImport) it seems that the [LSResourceAdapter](https://github.com/xmlresolver/xmlresolver/blob/b538b23ec609f03f26ab2a280cc896cd916dd57a/src/main/java/org/xmlresolver/adapters/LSResourceAdapter.java#L53) ignores them entirely when trying to resolve for xsd schema. I have tried writing my own LSResourceAdapter and substituting the namespaceId for the publicId, but still the lower level calls seem to ignore my catalog and still try to look up the namespaces as http URLs, rather than the redirected local file references that I want.

**Comment by ndw** [comment]
I thought there was a test for that. Thanks for the report. I'll investigate.

**Comment by pahjbo** [comment]
BTW - my catalogue entries are like 
```
<uri name="http://www.ivoa.net/xml/TAPRegExt/v1.0" uri="classpath:/schema/TAPRegExt-v1.0.xsd"/>
```

**Comment by pahjbo** [comment]
I can get a LSResourceAdapter that does what I expect by calling

```
 request = resolver.getRequest(namespaceURI);
```

see https://github.com/Javastro/ivoa-schemata/blob/master/src/main/java/org/javastro/ivoa/schema/LSResourceAdapter.java for full code

**Comment by ndw** [comment]
This was a bug. Fixed now.
