### ISSUE TITLE
Expected behaviour when catalogue resolution fails?

### ISSUE THREAD

**Issue by pahjbo** [xmlresolver/xmlresolver#51]
I might have a mistaken understanding, but I thought that in general the idea of XML catalogues is that they provide mappings for a subset of all possible URIs and therefore the behaviour of org.xmlresolver.Resolver.resolve(String, String)  seems wrong in returning null when passed href and base that are not in the catalogue. If the Resolver is to be used directly in for example Saxon, then if the href and base do form a valid URI, it should return a Source for that URI.

**Comment by pahjbo** [comment]
It seems that the above is part of a larger set of issues to do with local file names and catalogues that expect systemID as the key - they do not seem to be working as I would expect - I have create a PR #52 that includes more tests of the behaviour that I would expect.

**Comment by ndw** [comment]
The `javax.xml.transform.URIResolver` API defines `resolve()` to return:

> A Source object, or null if the href cannot be resolved, and the processor should try to resolve the URI itself.

If the catalog resolver can't find the resource locally, it returns `null` and the processor, for example Saxon, constructs the URI from the `href` and `base` parts and attempts to resolve it.

This has two advantages: first, it allows the processor to determine if catalog resolution succeeded or failed, and second, it moves exceptions for unresolvable URIs back into the processor.

**Comment by pahjbo** [comment]
> 
> If the catalog resolver can't find the resource locally, it returns `null` and the processor, for example Saxon, constructs the URI from the `href` and `base` parts and attempts to resolve it.
> 

as I realised in my comment above, I was being confused by my catalogue (which attempts to do some systemId manipulation) not working - see #52 for some tests of this

**Comment by ndw** [comment]
I've responded to #52, I think you just need to correct your catalog. I'm sorry this isn't clearer. The distinction between _system identifiers_ and _uris_ is not one that I think is especially helpful in modern times, but there is a lot of legacy that probably relies on this distinction so there's no easy way to simplify it now.

I suppose a flag for "just treat `system` and `uri` as synonyms for crying out loud" might not be entirely unreasonable.
