### ISSUE TITLE
Add support for JAXP 185: Restrict Fetching of External XML Resources

### ISSUE THREAD

**Issue by ndw** [xmlresolver/xmlresolver#76]
JAXP 185 allows a system to be configured such that some protocols will be rejected when resolving URIs. It explicitly states that it doesn't apply when a resolver is used. But the goal here, in the XML Resolver, is to encourage everyone to always use a resolver in order to reap the benefits of local resolution, caching, etc. So let's see if we can make the resolver play nice with JAXP 185.

Attempting to limit access via system properties suggests that the goal here is to prevent malicious users from attacking a system by making requests for resources from the filesystem, from the classpath, from jar files, etc. These are users with access to schemas or stylesheets, but not the system itself. If they had access to the system itself, they could use the `java.net.URI` class and they'd be unhampered by these properties.

It follows that we can assume a system that's using these properties has been configured by a reliable source. In other words, we're trying to thwart malicious users, not malicious systems integrators.

Next, there's the properties themselves which apply to DTD access, XML Schema access, and stylesheet access. These don't map well onto a modern system which also has to contend with other kinds of schema validation, access to unparsed text resources, etc.

It happens that because of the way the XML APIs developed on the Java platform, access to DTDs can be distinguished from access to other kinds of resources. But there's no reliable way, at the resolver level, to distinguish between XML Schema access, RELAXNG Schema access, XSL module access, XQuery module access, etc. (And, in fact, some libraries, especially older ones, use the DTD APIs for non-DTD resources, so it's all a bit muddled.)

Here's my proposal: if the restriction is enabled, requests to resolve URIs that are among the restricted protocols are rejected. The resolver returns `null` without any attempt to look them up. **But** if *resolution* returns a URI, that URI is used without restriction. 

This seems to be consistent with the intent. If I configure a system to lookup the DocBook schemas in a jar file, then they can be used in the jar file. But that doesn't mean the user can access random `jar:` URIs with the `doc()` function. (Using the feature this way will require a bit of care in the configuration. For example, the `MASK_JAR_URIS` feature will have to be enabled and all of the resources will have to be listed in the catalog as relative URI resolution against a `jar:` URI will fail.)

With respect to the properties, I propose that `accessExternalDTD` applies to the APIs that were designed for DTD access (resolving entities, system and public identifiers, etc.) Since the resolver can't know what other URI access is being attempted, the *union* of the `accessExternalSchema` and `accessExternalStylesheet` properties applies to the other resolver APIs.

(In principle, one could imagine making this more complicated by bringing nature and purpose into play, but given how shallow JSR 185 is with respect to the purposes considered, this doesn't seem worthwhile at the moment.)

**Comment by michaelhkay** [comment]
"requests to resolve URIs that are among the restricted protocols are rejected"

Suppose we don't want to allow http access in general. But we do want to allow access to specific http URIs, by redirecting the request to local copies -- or even by doing an HTTP access to an approved site?

I guess the catalog provides other ways of blocking selected URIs, e.g. `<rewriteSystem systemIdStartString="classpath:"
               rewritePrefix="disallowed:"/>`

So perhaps we're dealing more with a tick-box conformance requirement here. If you want fine-grained access control, define the rules in the catalog. If you just want coarse access control at protocol level, use the (inappropriately-named) properties like accessExternalStylesheet, and accept that they're crude.

That suggests your rule should work.

I would be inclined to have two properties in the resolver API, accessExternalEntity and accessExternalDocument, and it's up to the user of the API to decide how to map these to the three properties defined in JAXP 185.
