### ISSUE TITLE
NPE when resolving schema resource without systemId

### ISSUE THREAD

**Issue by chludwig-haufe** [xmlresolver/xmlresolver#99]
The description of [`LSResourceResolver.resolveResource(String type, String namespaceURI, String publicId, String systemId, String baseURI)`](https://docs.oracle.com/en/java/javase/11/docs/api//java.xml/org/w3c/dom/ls/LSResourceResolver.html#resolveResource(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)) explicitly allows `systemId` to be `null`. If `type` is `"http://www.w3.org/2001/XMLSchema"`, however, the implementation in [`org.xmlresolver.Resolver`](https://github.com/xmlresolver/xmlresolver/blob/d3a83655c6e0058a7e14931ce0f12175acd85497/src/main/java/org/xmlresolver/Resolver.java) (v4.3.0) throws a `NullPointerException`.

I encountered this when parsing an XML schema by means of the JDK's default implementation of `javax.xml.validation.SchemaFactory#newSchema(javax.xml.transform.Source)`. The schema in question contains (in some included schema document with file URL `baseSchemaDocURL`) an  element `<xs:import namespace="http://www.w3.org/1999/xhtml/datatypes/">`. (Note: no `schemaLocation` attribute!)

When processing this element, the factory calls `resolveResource("http://www.w3.org/2001/XMLSchema", "http://www.w3.org/1999/xhtml/datatypes/", null, null, baseSchemaDocURL)`. I'd expect the return value `null` so that the schema factory continues with its default handling of such `xs:import` elements.

**Comment by ndw** [comment]
I assume this is fixed by your PR.
